# root "/home/ivan/PROJECTS/cisloavocado";
# location /esim/admin {
#       root "/home/ivan/PROJECTS/esim_web/web/frontend/dist";
#       try_files $uri $uri/ /web/frontend/dist/index.html;
#     }

# location ~ ^/esim/admin/(.+\.(?:jpg|js|jpeg|gif|png|mp3|ico|css|woff|ttf|ico|woff2|zip|rar|pdf|svg|map))$ {
#     gzip on;
#     gzip_comp_level 5;
#     gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

#     alias /home/ivan/PROJECTS/esim_web/web/frontend/dist/$1;
# }

# location /esim/backend {
#     root "/home/ivan/PROJECTS/esim_web/web/backend/public";
#     index index.php index.html;
#     proxy_redirect   off;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Host $server_name;
#     proxy_set_header X-Forwarded-Proto $scheme;
#     try_files $uri $uri/ @esim_backend;
#     location ~ /esim/backend(/.+\.php)$ {
#         include        fastcgi_params;
#         fastcgi_pass   unix:/run/php/php7.4-fpm.sock;
#         fastcgi_param  SCRIPT_FILENAME $document_root$1;
#         fastcgi_index  index.php;
#     }
# }

# location @esim_backend {
#     rewrite /esim/backend/(.*)$ /esim/backend/index.php?/$1 last;
# }